apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svcandidates2021.fullname" . }}-config
data:
  SMTP_ENABLED: "{{ .Values.svcandidates2021.smtp.enabled }}"
  SMTP_HOST: "{{ .Values.svcandidates2021.smtp.host }}"
  SMTP_PORT: "{{ .Values.svcandidates2021.smtp.port }}"
  SMTP_USERNAME: "{{ .Values.svcandidates2021.smtp.username }}"
  SMTP_SSL_CONNECTION: "{{ .Values.svcandidates2021.smtp.ssl }}"
  SMTP_VERIFY_SSL_CERTIFICATE: "{{ .Values.svcandidates2021.smtp.ssl_ver }}"
  SMTP_FROM: "{{ .Values.svcandidates2021.smtp.from }}"
  PASSWORD_RESET_LINK_PATTERN: "{{ .Values.svcandidates2021.reset_password_url }}"
  SQL_USERNAME: "{{ tpl .Values.svcandidates2021.sql.username . }}"
  SQL_DBNAME: "{{ tpl .Values.svcandidates2021.sql.name . }}"
  SQL_HOST: "{{ tpl .Values.svcandidates2021.sql.host . }}"
  SQL_PORT: "{{ tpl .Values.svcandidates2021.sql.port . }}"
