{{- if .Values.svcandidates2021.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "svcandidates2021.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "svcandidates2021.name" . }}
    helm.sh/chart: {{ include "svcandidates2021.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.svcandidates2021.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.svcandidates2021.ingress.tls_enabled }}
  tls:
  {{- range .Values.svcandidates2021.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $serviceName := include "svcandidates2021.fullname" . -}}
  {{- range .Values.svcandidates2021.ingress.hosts }}
  - host: {{ .host.domain | quote }}
    http:
      paths:
      - path: {{ .host.path }}
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ .host.port }}
  {{- end }}
{{- end }}
