apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "svcandidates2021.fullname" . }}-secret
data:
  SQL_PASSWORD: {{ tpl .Values.svcandidates2021.sql.password . | b64enc | quote }}
  SMTP_PASSWORD: {{ tpl .Values.svcandidates2021.smtp.password . | b64enc | quote }}
